-- Stock Trading Bot Database Schema
-- SQLite implementation

-- Enable foreign keys and WAL mode for better performance
PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

-- 1. Instruments table
CREATE TABLE IF NOT EXISTS instruments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL UNIQUE,           -- e.g., 'AAPL', 'TSLA'
    name TEXT,                             -- Full company name
    exchange TEXT,                         -- e.g., 'NASDAQ', 'NYSE'
    currency TEXT DEFAULT 'USD',
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 2. Market data (OHLCV + timestamp)
CREATE TABLE IF NOT EXISTS market_data (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol_id INTEGER NOT NULL,
    timestamp DATETIME NOT NULL,           -- Time of the data point
    interval TEXT NOT NULL,                -- '1min', '5min', '1hour', '1day'
    open DECIMAL(15,6) NOT NULL,
    high DECIMAL(15,6) NOT NULL,
    low DECIMAL(15,6) NOT NULL,
    close DECIMAL(15,6) NOT NULL,
    volume BIGINT NOT NULL,
    vwap DECIMAL(15,6),                    -- Volume Weighted Average Price
    trade_count INTEGER,                   -- Number of trades in the interval
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (symbol_id) REFERENCES instruments(id),
    UNIQUE(symbol_id, timestamp, interval)
);

-- 3. Technical indicators (calculated from market data)
CREATE TABLE IF NOT EXISTS technical_indicators (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    market_data_id INTEGER NOT NULL,
    symbol_id INTEGER NOT NULL,
    timestamp DATETIME NOT NULL,
    interval TEXT NOT NULL,
    
    -- Moving Averages
    sma_20 DECIMAL(15,6),
    sma_50 DECIMAL(15,6),
    sma_200 DECIMAL(15,6),
    ema_12 DECIMAL(15,6),
    ema_26 DECIMAL(15,6),
    
    -- Bollinger Bands
    bb_upper DECIMAL(15,6),
    bb_middle DECIMAL(15,6),
    bb_lower DECIMAL(15,6),
    bb_width DECIMAL(15,6),
    
    -- RSI
    rsi_14 DECIMAL(10,6),
    
    -- MACD
    macd DECIMAL(15,6),
    macd_signal DECIMAL(15,6),
    macd_histogram DECIMAL(15,6),
    
    -- Volume indicators
    volume_sma DECIMAL(15,2),
    obv DECIMAL(15,2),                    -- On Balance Volume
    
    -- Support/Resistance
    support_level DECIMAL(15,6),
    resistance_level DECIMAL(15,6),
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (symbol_id) REFERENCES instruments(id),
    FOREIGN KEY (market_data_id) REFERENCES market_data(id),
    UNIQUE(symbol_id, timestamp, interval)
);

-- 4. Trading strategies
CREATE TABLE IF NOT EXISTS strategies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE,             -- e.g., 'mean_reversion', 'breakout'
    description TEXT,
    parameters JSON,                       -- Strategy-specific parameters
    category TEXT,
    strategy_type TEXT,
    stock_list_mode TEXT,
    stock_list TEXT,
    stock_list_ai_prompt TEXT,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 5. Trading signals generated by strategies
CREATE TABLE IF NOT EXISTS trading_signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol_id INTEGER NOT NULL,
    strategy_id INTEGER NOT NULL,
    timestamp DATETIME NOT NULL,
    signal_type TEXT NOT NULL,             -- 'BUY', 'SELL', 'HOLD'
    strength DECIMAL(10,6),               -- Signal strength (0-1 or -1 to 1)
    price DECIMAL(15,6),                  -- Price when signal was generated
    confidence DECIMAL(5,4),              -- Confidence level 0-1
    
    -- Signal metadata
    indicators_used JSON,                  -- Which indicators contributed
    reason TEXT,                          -- Human-readable reason for signal
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (symbol_id) REFERENCES instruments(id),
    FOREIGN KEY (strategy_id) REFERENCES strategies(id)
);

-- 6. Orders table
CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id TEXT NOT NULL,
    symbol_id INTEGER NOT NULL,
    strategy_id INTEGER NOT NULL,
    
    -- Order details
    order_id TEXT UNIQUE,                 -- Broker's order ID
    order_type TEXT NOT NULL,             -- 'MARKET', 'LIMIT', 'STOP'
    side TEXT NOT NULL,                   -- 'BUY', 'SELL'
    quantity DECIMAL(15,6) NOT NULL,
    price DECIMAL(15,6),                  -- Limit price for limit orders
    stop_price DECIMAL(15,6),             -- Stop price for stop orders
    
    -- Order status
    status TEXT NOT NULL,                 -- 'PENDING', 'FILLED', 'CANCELLED', 'REJECTED'
    filled_quantity DECIMAL(15,6) DEFAULT 0,
    average_fill_price DECIMAL(15,6),
    commission DECIMAL(10,2) DEFAULT 0,
    
    -- Timestamps
    submitted_at DATETIME,
    filled_at DATETIME,
    cancelled_at DATETIME,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    FOREIGN KEY (symbol_id) REFERENCES instruments(id),
    FOREIGN KEY (strategy_id) REFERENCES strategies(id)
);

-- 7. Portfolio positions
CREATE TABLE IF NOT EXISTS positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id TEXT NOT NULL,
    symbol_id INTEGER NOT NULL,
    quantity DECIMAL(15,6) NOT NULL DEFAULT 0,
    average_entry_price DECIMAL(15,6) NOT NULL,
    current_price DECIMAL(15,6),
    unrealized_pnl DECIMAL(15,6) DEFAULT 0,
    realized_pnl DECIMAL(15,6) DEFAULT 0,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    FOREIGN KEY (symbol_id) REFERENCES instruments(id),
    UNIQUE(account_id, symbol_id)
);

-- 8. Trade history (completed trades)
CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id TEXT NOT NULL,
    symbol_id INTEGER NOT NULL,
    strategy_id INTEGER NOT NULL,
    
    -- Trade details
    side TEXT NOT NULL,                   -- 'BUY', 'SELL'
    quantity DECIMAL(15,6) NOT NULL,
    entry_price DECIMAL(15,6) NOT NULL,
    exit_price DECIMAL(15,6) NOT NULL,
    
    -- P&L calculations
    gross_pnl DECIMAL(15,6) NOT NULL,
    commission DECIMAL(10,2) DEFAULT 0,
    net_pnl DECIMAL(15,6) NOT NULL,
    pnl_percentage DECIMAL(10,4),
    
    -- Timestamps
    entry_time DATETIME NOT NULL,
    exit_time DATETIME NOT NULL,
    holding_period_days INTEGER,
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (account_id) REFERENCES accounts (account_id),
    FOREIGN KEY (symbol_id) REFERENCES instruments(id),
    FOREIGN KEY (strategy_id) REFERENCES strategies(id)
);

-- 9. Accounts table
CREATE TABLE IF NOT EXISTS accounts (
    account_id TEXT PRIMARY KEY,
    account_name TEXT NOT NULL,           -- Display name for the account
    account_type TEXT NOT NULL DEFAULT 'virtual',  -- 'virtual', 'alpaca', etc.
    cash_balance DECIMAL(15,2) NOT NULL,
    currency TEXT DEFAULT 'USD',          -- Account currency
    status TEXT DEFAULT 'active',         -- 'active', 'inactive', 'suspended'
    description TEXT,                     -- Optional account description
    strategy_id INTEGER,                  -- Associated strategy (can be NULL)
    is_active BOOLEAN DEFAULT 1,          -- Soft delete flag
    
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (strategy_id) REFERENCES strategies(id)    
);

-- 10. System logs for debugging and monitoring
CREATE TABLE IF NOT EXISTS system_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    account_id TEXT,
    level TEXT NOT NULL,                  -- 'INFO', 'WARNING', 'ERROR', 'DEBUG'
    module TEXT,                          -- Which part of the system
    message TEXT NOT NULL,
    details TEXT,                         -- JSON or detailed error info

    FOREIGN KEY (account_id) REFERENCES accounts (account_id)
);

-- 11. Settings
CREATE TABLE IF NOT EXISTS settings (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT,
    name TEXT NOT NULL UNIQUE,             
    parameters JSON,                       
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes 
CREATE INDEX IF NOT EXISTS idx_market_data_symbol_timestamp ON market_data(symbol_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_market_data_timestamp ON market_data(timestamp);
CREATE INDEX IF NOT EXISTS idx_technical_indicators_symbol_timestamp ON technical_indicators(symbol_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_trading_signals_timestamp ON trading_signals(timestamp);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_submitted_at ON orders(submitted_at);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trades(entry_time);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON trades(symbol_id);
CREATE INDEX IF NOT EXISTS idx_system_logs_timestamp ON system_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_system_logs_level ON system_logs(level);
